### ISSUE TITLE
Fix giant images 

### ISSUE THREAD

**Issue by lisafast** [gc-proto/recalls-safety#4]
In desktop view, images are enormous. Resize please. 
@AlainGiroux with advice or help from @jmealing

**Comment by quidampepin** [comment]
Also, I'm thinking: images used to help identify the "product code" (the "identifying features") should not be in the carousel at the top, but rather in the Affected products section (see Stella Artois, Britax and Dumplings). The top image's purpose should be to help identify the product in general - in many cases, a single image should be fine (no need for a carousel in these cases).
