### ISSUE TITLE
Filterable responsive table: fix visual

### ISSUE THREAD

**Issue by quidampepin** [gc-proto/recalls-safety#7]
A few elements would need to be fixed on desktop view:
- Add lines between rows (or maybe a "zebra-type" design) to better differentiate the elements
- There is a sort feature at each column, but the arrows are not visible

**Comment by quidampepin** [comment]
Also: 
- put the "Show 10 entries" at the bottom
- put "showing x o y entries" at the top

**Comment by lisafast** [comment]
@AlainGiroux

**Comment by quidampepin** [comment]
Also: arrows for Previous and next (when there is more than one page of results) are not loading properly.

**Comment by AlainGiroux** [comment]
This has been done.
