### ISSUE TITLE
Fix UPC codes on sandwich 

### ISSUE THREAD

**Issue by lisafast** [gc-proto/recalls-safety#8]
The UPC codes were corrected to read more like the codes on the packages (with spaces) - in this recall. Please revise this page https://gc-proto.github.io/recalls-safety/scenarioH/roast_beef.html

to be like this page: http://www.healthycanadians.gc.ca/recall-alert-rappel-avis/inspection/2018/66554r-eng.php?_ga=2.15827510.1609307106.1526994094-669690414.1516300708

@AlainGiroux

**Comment by AlainGiroux** [comment]
This has been corrected.

Alain
