### ISSUE TITLE
3 bullets for Summary 

### ISSUE THREAD

**Issue by lisafast** [gc-proto/recalls-safety#9]
@quidampepin Do you want to take a stab at making 3 bullet summaries for ALL of the target templates? I think this has real value in enforcing a non-prose approach and helping teams keep them short and sweet. Or at least have a look at them all, and see if 3 bullets like the US would work or help or be useful. 

Or maybe they arent bullets on here - look how they become the search description. Quite cool. https://www.cpsc.gov/Recalls

**Comment by quidampepin** [comment]
3-bullet summary added to each target templates.

**Comment by quidampepin** [comment]
All bullets added.
